# Any message in this config is following MiniMessage format, for more, please head to https://docs.advntr.dev/minimessage/format.html
zoneId: ""
# If you wish to change timezone (for example if you have server in other country),
# write it there, otherwise leave "" for system's timezone
# Search for timezones here https://timezonedb.com/time-zones
# Example of valid timezone is Europe/Prague
notification:
  creative-tracking:
    message: "<red>Player <blue><player> <red>has clicked on item <gold><item></gold> in CREATIVE mode."
    # Replacements change material name, look on example for more info
    replacements:
      # The material name "DIRT" will be replaced with "CORRUPTED DIRT"
      # Look also how you can change color with MiniMessage
      DIRT: "<amount>x <dark_purple>CORRUPTED DIRT"
      # Stay uppercase, if any of the keys are lowercase, it won't work,
      # If material name has space instead of space replace it with _
      # This is meant just to key, value ("<purple>CORRUPTED DIRT") can be with spaces
  command-executed: "<red>Player <blue><player></blue> executed command <gold><command></gold>."
commands:
  insufficient-permissions: "<red>You do not have enough permissions to continue."
  reloaded-config: "<gold>Reloaded config.yml."
  reloaded-global-config: "<gold>Reloaded global_configuration.yml."
  notification:
    missing-type: "<red>Wrong command usage: <gold>/staffprotect notification subscribe/unsubscribe"
    enabled: "<gold>Notifications were enabled."
    disabled: "<gold>Notifications were disabled."
  addon:
    missing-name: "<red>Missing addon name."
    invalid-addon: "<red>Couldn't find addon with this name."
    missing-action: "<red>Missing action type (reload/enable/disable)."
    invalid-action: "<red>Couldn't find action type with this input."
    reloaded: "<gold>Reloaded addon <blue><addon>."
    enabled: "<gold>Enabled addon <blue><addon>."
    disabled: "<gold>Disabled addon <blue><addon>."
    already:
      disabled: "<red>Addon is already disabled."
      enabled: "<red>Addon is already enabled."