# Any message in this config is following MiniMessage format, for more, please head to https://docs.advntr.dev/minimessage/format.html
notification:
  creative-tracking:
    message: "<red>Player <blue><player> <red>has clicked on item <gold><item></gold> in CREATIVE mode."
    # Replacements change material name, look on example for more info
    replacements:
      # The material name "DIRT" will be replaced with "CORRUPTED DIRT"
      # Look also how you can change color with MiniMessage
      DIRT: "<amount>x <dark_purple>CORRUPTED DIRT"
      # Stay uppercase, if any of the keys are lowercase, it won't work,
      # If material name has space instead of space replace it with _
      # This is meant just to key, value ("<purple>CORRUPTED DIRT") can be with spaces
  command-executed: "<red>Player <blue><player></blue> executed command <gold><command></gold>."