name: StaffProtect
version: '${version}'
main: net.experience.powered.staffprotect.spigot.StaffProtectPlugin
api-version: '1.20'
authors:
  - "JakushCZ"
  - "Hitman"
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlin_version}"
  - "com.google.zxing:javase:3.5.1"
  - "net.kyori:adventure-api:4.3.0"
  - "net.kyori:adventure-platform-bukkit:4.3.0"
  - "net.kyori:adventure-platform-bungeecord:4.3.0"
  - "net.kyori:adventure-text-serializer-legacy:4.13.1"
  - "net.kyori:adventure-text-serializer-plain:4.14.0"
  - "net.kyori:adventure-text-minimessage:4.13.1"
  - "mysql:mysql-connector-java:8.0.33"